/**
 * src/settings/catalog.ts
 * Samsung Galaxy One UI Structured Troubleshooting Catalog & Plan Repository
 * 
 * Provides deterministic, structured troubleshooting plans for Samsung Galaxy S24 Ultra / One UI 6.1.
 * Covers: Battery, Network, Display, Storage/Performance, Notifications, and Apps.
 */

import type { Screen } from '../hooks/usePhoneNavigation';
import type { DeviceSettingKey } from './definitions';
import type { FixAction, RiskLevel } from './actions';

export interface FixDefinition {
  id: string;
  title: string;
  description: string;
  whyItHelps: string;
  expectedImpact: string;
  samsungPath: string[];
  action?: FixAction;
  risk: RiskLevel;
  canAutoApply: boolean;
  canDemo: boolean;
  prerequisites?: string[];
  capabilityId?: string;
}

export interface TroubleshootingPlan {
  problemId: string;
  title: string;
  category: 'Battery' | 'Network' | 'Display' | 'Storage / Performance' | 'Notifications' | 'Apps';
  diagnosis: string;
  likelyCauses: string[];
  fixes: FixDefinition[];
  keywords: string[];
}

export const TROUBLESHOOTING_CATALOG: TroubleshootingPlan[] = [
  // =========================================================================
  // 1. BATTERY CATEGORY
  // =========================================================================
  {
    problemId: 'battery-drain',
    title: 'Rapid Battery Drain',
    category: 'Battery',
    diagnosis: 'Excessive background processes, high screen refresh rates (120Hz), and unoptimized display brightness are accelerating battery discharge.',
    likelyCauses: [
      'Unrestricted background apps maintaining active CPU wakelocks',
      'Adaptive 120Hz display refresh rate drawing continuous GPU power',
      'High screen brightness on Dynamic AMOLED display',
      'Rogue apps consuming resources in the background',
    ],
    keywords: ['drain', 'battery draining', 'battery drop', 'dying fast', 'losing battery', 'battery backup', 'jaldi khatam', 'battery dies'],
    fixes: [
      {
        id: 'fix-power-saving',
        title: 'Turn on Power Saving Mode',
        description: 'Limits CPU performance to 70%, lowers display brightness by 10%, and restricts background data.',
        whyItHelps: 'Instantly caps maximum processor power draw and halts unnecessary background synchronizations.',
        expectedImpact: 'Extends screen-on time by 1.5 to 2.5 hours',
        samsungPath: ['Settings', 'Battery', 'Power saving'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'power_saving',
        action: {
          id: 'fix-power-saving',
          title: 'Turn on Power Saving Mode',
          type: 'TOGGLE_ON',
          settingKey: 'powerSaving',
          targetValue: true,
          destination: 'settings/battery',
          destinationPath: ['Settings', 'Battery', 'Power saving'],
          highlightNode: 'Power saving',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Extends battery life by up to 2.5 hours',
          reason: 'Throttles peak CPU clocks, turns off Always On Display, and restricts background syncing.',
          steps: ['Open Settings', 'Tap Battery', 'Toggle Power saving to ON'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Power saving', durationMs: 700 },
            { type: 'TOGGLE', target: 'powerSaving', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Power saving enabled in Fixby simulator' },
          ],
        },
      },
      {
        id: 'fix-deep-sleeping-apps',
        title: 'Put High Drain Apps to Deep Sleep',
        description: 'Deep sleeping apps will never run in the background and only receive updates when actively opened.',
        whyItHelps: 'Eliminates 100% of background wakelocks and rogue process loops from non-essential third-party apps.',
        expectedImpact: 'Stops 20% - 35% of idle standby battery drain',
        samsungPath: ['Settings', 'Battery', 'Background usage limits', 'Deep sleeping apps'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'deep_sleeping_apps',
        action: {
          id: 'fix-deep-sleeping-apps',
          title: 'Put High Drain Apps to Deep Sleep',
          type: 'CONFIG_CHANGE',
          settingKey: 'deepSleepingAppsCount',
          targetValue: 8,
          destination: 'settings/battery-usage',
          destinationPath: ['Settings', 'Battery', 'Background usage limits', 'Deep sleeping apps'],
          highlightNode: 'Deep sleeping apps',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Stops rogue background app wakelocks',
          reason: 'Deep sleeping apps are completely prevented from waking up until launched.',
          steps: ['Open Settings', 'Tap Battery', 'Tap Background usage limits', 'Add apps to Deep sleeping'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery-usage', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Put apps to sleep', durationMs: 700 },
            { type: 'CONFIG_CHANGE', target: 'deepSleepingAppsCount', value: 8, durationMs: 600 },
            { type: 'COMPLETE', message: 'High-drain apps moved to Deep Sleep' },
          ],
        },
      },
      {
        id: 'fix-dark-mode-battery',
        title: 'Turn on Dark Mode',
        description: 'Switches system interface and supported apps to black OLED theme.',
        whyItHelps: 'Individual OLED subpixels turn off completely when displaying black, consuming 0 milliwatts of power.',
        expectedImpact: 'Saves 15% - 25% battery on Dynamic AMOLED displays',
        samsungPath: ['Settings', 'Display', 'Dark mode'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'dark_mode',
        action: {
          id: 'fix-dark-mode-battery',
          title: 'Turn on Dark Mode',
          type: 'TOGGLE_ON',
          settingKey: 'darkMode',
          targetValue: true,
          destination: 'settings/display',
          destinationPath: ['Settings', 'Display', 'Dark mode'],
          highlightNode: 'Dark mode',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Saves ~20% battery on Dynamic AMOLED displays',
          reason: 'True black pixels on Samsung OLED panels are completely powered off.',
          steps: ['Open Settings', 'Tap Display', 'Select Dark mode'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/display', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Dark mode', durationMs: 700 },
            { type: 'TOGGLE', target: 'darkMode', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Dark mode enabled' },
          ],
        },
      },
      {
        id: 'fix-motion-smoothness-60hz',
        title: 'Switch Motion Smoothness to Standard (60Hz)',
        description: 'Locks screen refresh rate to standard 60Hz instead of Adaptive 120Hz.',
        whyItHelps: 'Halves the display controller driving cycles and reduces graphics processor rendering workloads.',
        expectedImpact: '+1.5 hours extra battery life per day',
        samsungPath: ['Settings', 'Display', 'Motion smoothness', 'Standard'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'motion_smoothness',
        action: {
          id: 'fix-motion-smoothness-60hz',
          title: 'Set Motion Smoothness to Standard (60Hz)',
          type: 'CONFIG_CHANGE',
          settingKey: 'motionSmoothness',
          targetValue: 'Standard',
          destination: 'settings/motion-smoothness',
          destinationPath: ['Settings', 'Display', 'Motion smoothness'],
          highlightNode: 'Standard',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: '+1.5 hours extra screen-on time',
          reason: 'Standard 60Hz reduces the GPU display refresh load by 50%.',
          steps: ['Open Settings', 'Tap Display', 'Tap Motion smoothness', 'Select Standard'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/display', durationMs: 600 },
            { type: 'NAVIGATE', screen: 'settings/display/motion-smoothness', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Standard', durationMs: 700 },
            { type: 'CONFIG_CHANGE', target: 'motionSmoothness', value: 'Standard', durationMs: 500 },
            { type: 'COMPLETE', message: 'Motion smoothness set to Standard (60Hz)' },
          ],
        },
      },
      {
        id: 'fix-performance-profile-light',
        title: 'Switch to Light Performance Profile',
        description: 'Prioritizes battery efficiency and cooling over maximum clock speeds without affecting games.',
        whyItHelps: 'Prevents the processor from boosting to excessive frequencies during routine app tasks.',
        expectedImpact: '10% - 15% lower processor battery consumption',
        samsungPath: ['Settings', 'Device care', 'Performance profile', 'Light'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'performance_profile',
        action: {
          id: 'fix-performance-profile-light',
          title: 'Switch to Light Performance Profile',
          type: 'CONFIG_CHANGE',
          settingKey: 'performanceProfile',
          targetValue: 'Light',
          destination: 'settings/device-care',
          destinationPath: ['Settings', 'Device care', 'Performance profile'],
          highlightNode: 'Performance profile',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: '-4°C to -6°C temperature drop and 10% battery savings',
          reason: 'Adjusts processing speed to favor battery life and cooling without affecting games.',
          steps: ['Open Settings', 'Tap Device care', 'Tap Performance profile', 'Select Light'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/device-care', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Performance profile', durationMs: 700 },
            { type: 'CONFIG_CHANGE', target: 'performanceProfile', value: 'Light', durationMs: 500 },
            { type: 'COMPLETE', message: 'Performance profile set to Light mode' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'phone-heating',
    title: 'Phone Overheating & Thermal Throttling',
    category: 'Battery',
    diagnosis: 'Sustained high CPU/GPU frequency scaling, 120Hz display refresh, or heavy background computation causing chassis thermal buildup.',
    likelyCauses: [
      'Heavy background computation or runaway system indexing',
      'Processor boosting to maximum turbo clocks during sustained tasks',
      'High screen refresh rate combined with high brightness',
      'Fast charging under direct sunlight or while gaming',
    ],
    keywords: ['overheat', 'overheating', 'hot', 'garam', 'phone hot', 'heating up', 'warm to touch', 'thermal'],
    fixes: [
      {
        id: 'fix-thermal-profile-light',
        title: 'Switch to Light Performance Profile',
        description: 'Prioritizes cooling and thermal dissipation by capping maximum CPU burst clock states.',
        whyItHelps: 'Significantly drops the thermal wattage generated by the Snapdragon 8 Gen 3 chipset.',
        expectedImpact: 'Reduces chassis temperature by 4°C to 6°C',
        samsungPath: ['Settings', 'Device care', 'Performance profile', 'Light'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'performance_profile',
        action: {
          id: 'fix-thermal-profile-light',
          title: 'Switch to Light Performance Profile',
          type: 'CONFIG_CHANGE',
          settingKey: 'performanceProfile',
          targetValue: 'Light',
          destination: 'settings/device-care',
          destinationPath: ['Settings', 'Device care', 'Performance profile'],
          highlightNode: 'Performance profile',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: '-4°C to -6°C temperature drop during heavy tasks',
          reason: 'Adjusts processing speed to favor cooling without affecting gaming performance.',
          steps: ['Open Settings', 'Tap Device care', 'Tap Performance profile', 'Select Light'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/device-care', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Performance profile', durationMs: 700 },
            { type: 'CONFIG_CHANGE', target: 'performanceProfile', value: 'Light', durationMs: 500 },
            { type: 'COMPLETE', message: 'Performance profile set to Light mode' },
          ],
        },
      },
      {
        id: 'fix-game-booster-thermal',
        title: 'Enable Game Booster Thermal Management',
        description: 'Activates automatic thermal throttling and FPS stabilization in Game Booster settings.',
        whyItHelps: 'Prevents the graphics processor from spiking temperatures past 42°C during intensive 3D rendering.',
        expectedImpact: 'Prevents thermal shutdown and erratic frame drops',
        samsungPath: ['Settings', 'Advanced features', 'Game Booster', 'Thermal management'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'game_booster_thermal',
        action: {
          id: 'fix-game-booster-thermal',
          title: 'Enable Thermal Management in Game Booster',
          type: 'TOGGLE_ON',
          settingKey: 'gameBoosterThermal',
          targetValue: true,
          destination: 'settings/advanced',
          destinationPath: ['Settings', 'Advanced features', 'Game Booster', 'Thermal management'],
          highlightNode: 'Thermal management',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Prevents thermal overheating spikes',
          reason: 'Actively throttles excessive heat during sustained gaming and heavy computing workloads.',
          steps: ['Open Settings', 'Tap Advanced features', 'Tap Game Booster', 'Toggle Thermal management to ON'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/advanced', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Thermal management', durationMs: 700 },
            { type: 'TOGGLE', target: 'gameBoosterThermal', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Thermal management enabled' },
          ],
        },
      },
      {
        id: 'fix-overheating-deep-sleep',
        title: 'Put Background Apps to Deep Sleep',
        description: 'Prevents rogue applications from looping in the background and heating the device.',
        whyItHelps: 'Stops background services from utilizing CPU cores when the screen is turned off.',
        expectedImpact: 'Eliminates idle heating in pockets',
        samsungPath: ['Settings', 'Battery', 'Background usage limits', 'Deep sleeping apps'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'deep_sleeping_apps',
        action: {
          id: 'fix-overheating-deep-sleep',
          title: 'Put High Drain Apps to Deep Sleep',
          type: 'CONFIG_CHANGE',
          settingKey: 'deepSleepingAppsCount',
          targetValue: 8,
          destination: 'settings/battery-usage',
          destinationPath: ['Settings', 'Battery', 'Background usage limits', 'Deep sleeping apps'],
          highlightNode: 'Deep sleeping apps',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Stops rogue background app CPU looping',
          reason: 'Deep sleeping apps are completely prevented from running until explicitly launched.',
          steps: ['Open Settings', 'Tap Battery', 'Tap Background usage limits', 'Add apps to Deep sleeping'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery-usage', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Put apps to sleep', durationMs: 700 },
            { type: 'CONFIG_CHANGE', target: 'deepSleepingAppsCount', value: 8, durationMs: 600 },
            { type: 'COMPLETE', message: 'Background apps put to Deep Sleep' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'battery-protection',
    title: 'Battery Health & Longevity Protection',
    category: 'Battery',
    diagnosis: 'Continuous charging to 100% and overnight trickle charging causes high electrochemical cell stress over time.',
    likelyCauses: [
      'Keeping phone plugged in overnight at 100% capacity',
      'High operating temperatures during high-voltage charging',
      'Unrestricted charge cycles causing lithium plating degradation',
    ],
    keywords: ['protect battery', 'battery protection', 'battery health', '85%', 'limit charge', 'maximum charge', 'overcharge', 'overnight charge'],
    fixes: [
      {
        id: 'fix-protect-battery',
        title: 'Enable Battery Protection (85% Limit)',
        description: 'Stops charging automatically when battery reaches 85% to preserve battery lifespan.',
        whyItHelps: 'Prevents chemical degradation caused by staying at 4.45V cell saturation for prolonged periods.',
        expectedImpact: 'Extends long-term battery lifespan by up to 200%',
        samsungPath: ['Settings', 'Battery', 'Protect battery'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'protect_battery',
        action: {
          id: 'fix-protect-battery',
          title: 'Enable Battery Protection',
          type: 'TOGGLE_ON',
          settingKey: 'protectBattery',
          targetValue: true,
          destination: 'settings/battery',
          destinationPath: ['Settings', 'Battery', 'Protect battery'],
          highlightNode: 'Protect battery',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Extends long-term battery lifespan by 200%',
          reason: 'Caps charge level at 85% to prevent high-voltage chemical stress on the lithium cells.',
          steps: ['Open Settings', 'Tap Battery', 'Toggle Protect battery to ON'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Protect battery', durationMs: 700 },
            { type: 'TOGGLE', target: 'protectBattery', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Battery protection enabled (capped at 85%)' },
          ],
        },
      },
      {
        id: 'fix-adaptive-battery',
        title: 'Turn on Adaptive Battery',
        description: 'Uses on-device machine learning to limit battery usage for rarely used applications.',
        whyItHelps: 'Dynamically optimizes background power delivery based on individual usage routines.',
        expectedImpact: 'Improves overall daily efficiency by 10% - 15%',
        samsungPath: ['Settings', 'Battery', 'More battery settings', 'Adaptive battery'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'adaptive_battery',
        action: {
          id: 'fix-adaptive-battery',
          title: 'Turn on Adaptive Battery',
          type: 'TOGGLE_ON',
          settingKey: 'adaptiveBattery',
          targetValue: true,
          destination: 'settings/battery',
          destinationPath: ['Settings', 'Battery', 'More battery settings', 'Adaptive battery'],
          highlightNode: 'Adaptive battery',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Improves daily efficiency by 15%',
          reason: 'Limits battery power for apps that you do not use often.',
          steps: ['Open Settings', 'Tap Battery', 'Tap More battery settings', 'Toggle Adaptive battery to ON'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Adaptive battery', durationMs: 700 },
            { type: 'TOGGLE', target: 'adaptiveBattery', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Adaptive battery enabled' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'slow-charging',
    title: 'Slow Charging & Cable Issues',
    category: 'Battery',
    diagnosis: 'Fast charging disabled in settings, degraded USB cable, or lint in the charging port limiting wattage handshake.',
    likelyCauses: [
      'Fast charging toggle disabled in One UI battery settings',
      'Incompatible power delivery adapter (requires USB PD PPS 45W)',
      'High device temperature throttling charging current for safety',
    ],
    keywords: ['slow charge', 'charging slow', 'slow charging', 'won\'t charge fast', 'not fast charging', 'charge nahi ho raha'],
    fixes: [
      {
        id: 'fix-enable-fast-charge-settings',
        title: 'Inspect Battery Charging Settings',
        description: 'Verify Fast charging and Super fast charging protocols are active in One UI settings.',
        whyItHelps: 'Ensures the battery controller negotiates the full 45W / 25W PPS protocol with your wall adapter.',
        expectedImpact: 'Charges up to 70% in 30 minutes with supported 45W PPS charger',
        samsungPath: ['Settings', 'Battery', 'More battery settings', 'Fast charging'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'power_saving',
        action: {
          id: 'fix-enable-fast-charge-settings',
          title: 'Inspect Battery Settings',
          type: 'NAVIGATE',
          destination: 'settings/battery',
          destinationPath: ['Settings', 'Battery', 'More battery settings'],
          highlightNode: 'Fast charging',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Restores high-wattage charging speed',
          reason: 'Opens One UI charging configurations to verify Fast Charging toggles.',
          steps: ['Open Settings', 'Tap Battery', 'Tap More battery settings', 'Turn on Fast charging and Fast wireless charging'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'More battery settings', durationMs: 700 },
            { type: 'COMPLETE', message: 'Inspected Fast Charging configurations' },
          ],
        },
      },
      {
        id: 'fix-cooldown-for-charging',
        title: 'Enable Light Performance Profile during Charging',
        description: 'Lowers baseline operating temperature so charging controller doesn\'t thermal throttle.',
        whyItHelps: 'Galaxy devices automatically halve charging speed if battery temperature exceeds 37°C.',
        expectedImpact: 'Prevents thermal charging throttling',
        samsungPath: ['Settings', 'Device care', 'Performance profile'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'performance_profile',
      },
    ],
  },

  // =========================================================================
  // 2. NETWORK CATEGORY
  // =========================================================================
  {
    problemId: 'wifi-not-connecting',
    title: 'Wi-Fi Not Connecting or Disconnecting Repeatedly',
    category: 'Network',
    diagnosis: 'Weak wireless handshake, DHCP lease conflicts, or aggressive network switching causing Wi-Fi instability.',
    likelyCauses: [
      'Stale DHCP IP lease or router DNS caching conflict',
      'Intelligent Wi-Fi switching aggressively between Wi-Fi and mobile data',
      'Corrupt network adapter cache or saved profile credentials',
    ],
    keywords: ['wifi', 'wi-fi', 'wifi not connecting', 'wifi disconnects', 'wifi dropping', 'wifi unstable', 'wifi keeps dropping', 'internet not working'],
    fixes: [
      {
        id: 'fix-intelligent-wifi',
        title: 'Enable Intelligent Wi-Fi',
        description: 'Detects unstable Wi-Fi signals and seamlessly fails over to mobile data without interrupting connections.',
        whyItHelps: 'Avoids connection freezing when moving between rooms or edge-of-range wireless signals.',
        expectedImpact: 'Eliminates Wi-Fi dropouts & connection stalling',
        samsungPath: ['Settings', 'Connections', 'Wi-Fi', 'Intelligent Wi-Fi'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'intelligent_wifi',
        action: {
          id: 'fix-intelligent-wifi',
          title: 'Enable Intelligent Wi-Fi',
          type: 'TOGGLE_ON',
          settingKey: 'intelligentWifi',
          targetValue: true,
          destination: 'settings/connections',
          destinationPath: ['Settings', 'Connections', 'Wi-Fi', 'Intelligent Wi-Fi'],
          highlightNode: 'Intelligent Wi-Fi',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Eliminates Wi-Fi dropouts & stalling',
          reason: 'Automatically detects weak signal and fails over smoothly to mobile data before connection drops.',
          steps: ['Open Settings', 'Tap Connections', 'Tap Wi-Fi', 'Turn on Intelligent Wi-Fi'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/connections', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Intelligent Wi-Fi', durationMs: 700 },
            { type: 'TOGGLE', target: 'intelligentWifi', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Intelligent Wi-Fi enabled' },
          ],
        },
      },
      {
        id: 'fix-toggle-wifi-radio',
        title: 'Restart Wi-Fi Radio',
        description: 'Cycles the wireless interface hardware off and on to renew the DHCP lease.',
        whyItHelps: 'Forces a fresh four-way WPA handshake with the local wireless access point.',
        expectedImpact: 'Quickly resolves 80% of local IP address conflicts',
        samsungPath: ['Settings', 'Connections', 'Wi-Fi'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'wifi_toggle',
        action: {
          id: 'fix-toggle-wifi-radio',
          title: 'Cycle Wi-Fi Radio',
          type: 'TOGGLE_ON',
          settingKey: 'wifi',
          targetValue: true,
          destination: 'settings/connections',
          destinationPath: ['Settings', 'Connections', 'Wi-Fi'],
          highlightNode: 'Wi-Fi',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Re-establishes router handshake',
          reason: 'Restarts the local 802.11 receiver to clear stale gateway socket state.',
          steps: ['Open Settings', 'Tap Connections', 'Turn Wi-Fi off, wait 3 seconds, then turn back on'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/connections', durationMs: 600 },
            { type: 'TOGGLE', target: 'wifi', value: false, durationMs: 500 },
            { type: 'WAIT', durationMs: 300 },
            { type: 'TOGGLE', target: 'wifi', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Wi-Fi radio cycled and reconnected' },
          ],
        },
      },
      {
        id: 'fix-reset-network-settings',
        title: 'Reset Network Settings',
        description: 'Restores Wi-Fi, Mobile Data, and Bluetooth settings to factory defaults. Personal data is not affected.',
        whyItHelps: 'Clears corrupt network routing tables, invalid APN entries, and broken wireless driver states.',
        expectedImpact: 'Full clean slate for all network interfaces',
        samsungPath: ['Settings', 'General management', 'Reset', 'Reset network settings'],
        risk: 'medium',
        canAutoApply: false,
        canDemo: true,
        capabilityId: 'network_reset',
        action: {
          id: 'fix-reset-network-settings',
          title: 'Reset Network Settings',
          type: 'NAVIGATE',
          destination: 'settings/general',
          destinationPath: ['Settings', 'General management', 'Reset', 'Reset network settings'],
          highlightNode: 'Reset network settings',
          requiresConfirmation: true,
          confirmationTitle: 'Reset Network Settings?',
          confirmationMessage: 'This will reset all network settings, including Wi-Fi, Mobile data, and Bluetooth. You will need to reconnect to Wi-Fi networks.',
          canAutoApply: false,
          risk: 'medium',
          estimatedImpact: 'Restores factory network drivers',
          reason: 'Requires native Android integration to purge system Wi-Fi credentials.',
          steps: ['Open Settings', 'Tap General management', 'Tap Reset', 'Tap Reset network settings', 'Tap Reset settings'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/general', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Reset network settings', durationMs: 700 },
            { type: 'COMPLETE', message: 'Navigated to Network Reset' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'bluetooth-not-connecting',
    title: 'Bluetooth Not Connecting or Disconnecting',
    category: 'Network',
    diagnosis: 'Bluetooth cache corruption, stale accessory pairing keys, or wireless radio interference.',
    likelyCauses: [
      'Corrupt pairing cache with target accessory (Galaxy Buds, smartwatch, car)',
      'Multiple paired devices competing for connection priority',
      'Bluetooth power management sleep restrictions',
    ],
    keywords: ['bluetooth', 'bluetooth not connecting', 'bluetooth disconnects', 'buds not connecting', 'bluetooth audio', 'bluetooth dropping'],
    fixes: [
      {
        id: 'fix-cycle-bluetooth',
        title: 'Cycle Bluetooth Radio',
        description: 'Disables and re-enables the Bluetooth radio to restart the HCI stack.',
        whyItHelps: 'Clears temporary socket locks and starts a fresh discovery scan.',
        expectedImpact: 'Re-establishes pairing handshake with nearby accessories',
        samsungPath: ['Settings', 'Connections', 'Bluetooth'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'bluetooth_toggle',
        action: {
          id: 'fix-cycle-bluetooth',
          title: 'Cycle Bluetooth Radio',
          type: 'TOGGLE_ON',
          settingKey: 'bluetooth',
          targetValue: true,
          destination: 'settings/connections',
          destinationPath: ['Settings', 'Connections', 'Bluetooth'],
          highlightNode: 'Bluetooth',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Restarts Bluetooth subsystem',
          reason: 'Turns Bluetooth off and on to restart device discovery.',
          steps: ['Open Settings', 'Tap Connections', 'Toggle Bluetooth off and back on'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/connections', durationMs: 600 },
            { type: 'TOGGLE', target: 'bluetooth', value: false, durationMs: 400 },
            { type: 'WAIT', durationMs: 300 },
            { type: 'TOGGLE', target: 'bluetooth', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Bluetooth radio cycled' },
          ],
        },
      },
      {
        id: 'fix-unpair-re-pair',
        title: 'Unpair and Re-pair Bluetooth Accessory',
        description: 'Removes the saved device profile from Samsung Connections and initiates a new pairing.',
        whyItHelps: 'Eliminates corrupted encryption keys and handshake state between phone and accessory.',
        expectedImpact: 'Fixes persistent pairing failures and audio stutter',
        samsungPath: ['Settings', 'Connections', 'Bluetooth', 'Paired devices'],
        risk: 'low',
        canAutoApply: false,
        canDemo: true,
        capabilityId: 'bluetooth_toggle',
      },
    ],
  },
  {
    problemId: 'mobile-data-not-working',
    title: 'Mobile Data Not Working',
    category: 'Network',
    diagnosis: 'Cellular data toggle off, APN misconfiguration, or network roaming block on carrier network.',
    likelyCauses: [
      'Mobile data disabled or data limit cap reached',
      'Flight mode radio lock requiring baseband restart',
      'Outdated Access Point Names (APN) configuration from carrier',
    ],
    keywords: ['mobile data', 'cellular data', 'data not working', '4g not working', '5g not working', 'no internet mobile'],
    fixes: [
      {
        id: 'fix-toggle-mobile-data',
        title: 'Turn on Mobile Data',
        description: 'Ensures cellular 5G/LTE data radio is active in One UI Connections.',
        whyItHelps: 'Directly powers the baseband cellular data transceiver.',
        expectedImpact: 'Restores instant cellular connectivity',
        samsungPath: ['Settings', 'Connections', 'Data usage', 'Mobile data'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'mobile_data',
        action: {
          id: 'fix-toggle-mobile-data',
          title: 'Turn on Mobile Data',
          type: 'TOGGLE_ON',
          settingKey: 'mobileData',
          targetValue: true,
          destination: 'settings/connections',
          destinationPath: ['Settings', 'Connections', 'Data usage', 'Mobile data'],
          highlightNode: 'Mobile data',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Restores 5G/LTE internet access',
          reason: 'Ensures cellular data toggle is active.',
          steps: ['Open Settings', 'Tap Connections', 'Tap Data usage', 'Turn on Mobile data'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/connections', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Mobile data', durationMs: 600 },
            { type: 'TOGGLE', target: 'mobileData', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Mobile data enabled' },
          ],
        },
      },
      {
        id: 'fix-toggle-flight-mode',
        title: 'Cycle Flight Mode to Reconnect Cell Towers',
        description: 'Toggles Airplane Mode ON for 5 seconds and OFF to force cell tower reconnection.',
        whyItHelps: 'Forces the modem baseband processor to register anew with the nearest carrier cell tower.',
        expectedImpact: 'Resolves carrier signal dead-zones and stalled 5G handoffs',
        samsungPath: ['Settings', 'Connections', 'Flight mode'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'flight_mode',
      },
    ],
  },

  // =========================================================================
  // 3. DISPLAY CATEGORY
  // =========================================================================
  {
    problemId: 'screen-brightness',
    title: 'Screen Brightness & Auto Brightness Issues',
    category: 'Display',
    diagnosis: 'Adaptive brightness sensor learning skewed by unusual lighting, or manual brightness slider override.',
    likelyCauses: [
      'Adaptive brightness algorithm learned skewed lighting preferences',
      'Proximity/ambient light sensor blocked by screen protector or dust',
      'Extra brightness feature disabled in direct outdoor sunlight',
    ],
    keywords: ['brightness', 'auto brightness', 'adaptive brightness', 'screen too dim', 'screen too dark', 'screen brightness', 'can\'t see screen', 'sunlight'],
    fixes: [
      {
        id: 'fix-adaptive-brightness',
        title: 'Enable Adaptive Brightness',
        description: 'Uses ambient light sensor to continuously calibrate screen lumen output to surrounding environment.',
        whyItHelps: 'Automatically boosts brightness in sunlight and dims display in dark rooms to prevent eye fatigue.',
        expectedImpact: 'Optimal visibility in all lighting conditions',
        samsungPath: ['Settings', 'Display', 'Adaptive brightness'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'auto_brightness',
        action: {
          id: 'fix-adaptive-brightness',
          title: 'Enable Adaptive Brightness',
          type: 'TOGGLE_ON',
          settingKey: 'autoBrightness',
          targetValue: true,
          destination: 'settings/display',
          destinationPath: ['Settings', 'Display', 'Adaptive brightness'],
          highlightNode: 'Adaptive brightness',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Optimal lumen output anywhere',
          reason: 'Allows the ambient sensor to calibrate screen brightness dynamically.',
          steps: ['Open Settings', 'Tap Display', 'Toggle Adaptive brightness to ON'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/display', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Adaptive brightness', durationMs: 700 },
            { type: 'TOGGLE', target: 'autoBrightness', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Adaptive brightness enabled' },
          ],
        },
      },
      {
        id: 'fix-eye-comfort-shield',
        title: 'Turn on Eye Comfort Shield',
        description: 'Filters out blue light wavelengths and shifts screen to a warmer, softer color temperature.',
        whyItHelps: 'Relieves eye strain during nighttime reading and prevents sleep cycle disruptions.',
        expectedImpact: 'Significantly reduces eye fatigue in the dark',
        samsungPath: ['Settings', 'Display', 'Eye comfort shield'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'eye_comfort_shield',
        action: {
          id: 'fix-eye-comfort-shield',
          title: 'Turn on Eye Comfort Shield',
          type: 'TOGGLE_ON',
          settingKey: 'eyeComfortShield',
          targetValue: true,
          destination: 'settings/display',
          destinationPath: ['Settings', 'Display', 'Eye comfort shield'],
          highlightNode: 'Eye comfort shield',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Reduces blue light strain by 70%',
          reason: 'Shifts display color balance toward warm spectrum.',
          steps: ['Open Settings', 'Tap Display', 'Toggle Eye comfort shield to ON'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/display', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Eye comfort shield', durationMs: 700 },
            { type: 'TOGGLE', target: 'eyeComfortShield', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Eye Comfort Shield enabled' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'motion-smoothness',
    title: 'Screen Stutter & 120Hz Refresh Rate',
    category: 'Display',
    diagnosis: 'Display controller locked to standard 60Hz or power saving throttle preventing Adaptive 120Hz rendering.',
    likelyCauses: [
      'Standard 60Hz selected in Motion smoothness settings',
      'Power saving mode automatically clamping refresh rate to 60Hz',
      'Thermal protection temporarily capping refresh rate',
    ],
    keywords: ['120hz', 'refresh rate', 'motion smoothness', 'screen stutter', 'stuttering display', 'lag screen', 'not smooth', '60hz'],
    fixes: [
      {
        id: 'fix-adaptive-120hz',
        title: 'Enable Adaptive 120Hz Motion Smoothness',
        description: 'Switches display refresh rate to Adaptive 120Hz for fluid scrolling and silky animations.',
        whyItHelps: 'Refreshes up to 120 frames per second, making UI touch response feel instantaneous.',
        expectedImpact: 'Silky smooth animations and zero scrolling stutter',
        samsungPath: ['Settings', 'Display', 'Motion smoothness', 'Adaptive'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'motion_smoothness',
        action: {
          id: 'fix-adaptive-120hz',
          title: 'Enable Adaptive 120Hz Smoothness',
          type: 'CONFIG_CHANGE',
          settingKey: 'motionSmoothness',
          targetValue: 'Adaptive',
          destination: 'settings/motion-smoothness',
          destinationPath: ['Settings', 'Display', 'Motion smoothness'],
          highlightNode: 'Adaptive',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Silky smooth 120Hz UI animations',
          reason: 'Adaptive mode refreshes up to 120 times per second for stutter-free scrolling.',
          steps: ['Open Settings', 'Tap Display', 'Tap Motion smoothness', 'Select Adaptive'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/display', durationMs: 600 },
            { type: 'NAVIGATE', screen: 'settings/display/motion-smoothness', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Adaptive', durationMs: 700 },
            { type: 'CONFIG_CHANGE', target: 'motionSmoothness', value: 'Adaptive', durationMs: 500 },
            { type: 'COMPLETE', message: 'Motion smoothness set to Adaptive (120Hz)' },
          ],
        },
      },
      {
        id: 'fix-turn-off-power-saving-120hz',
        title: 'Turn off Power Saving to Unlock 120Hz',
        description: 'Disables Power Saving mode which forcibly clamps display refresh rate to 60Hz.',
        whyItHelps: 'Power saving mode locks GPU rendering to 60Hz. Turning it off immediately restores high refresh rate.',
        expectedImpact: 'Restores silky 120Hz display refresh across all apps',
        samsungPath: ['Settings', 'Battery', 'Power saving'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'power_saving',
        action: {
          id: 'fix-turn-off-power-saving-120hz',
          title: 'Turn off Power Saving',
          type: 'TOGGLE_OFF',
          settingKey: 'powerSaving',
          targetValue: false,
          destination: 'settings/battery',
          destinationPath: ['Settings', 'Battery', 'Power saving'],
          highlightNode: 'Power saving',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Restores 120Hz refresh rate',
          reason: 'Turns off Power saving to enable high frame rate display.',
          steps: ['Open Settings', 'Tap Battery', 'Toggle Power saving to OFF'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Power saving', durationMs: 700 },
            { type: 'TOGGLE', target: 'powerSaving', value: false, durationMs: 500 },
            { type: 'COMPLETE', message: 'Power saving turned off, 120Hz unlocked' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'accidental-touch',
    title: 'Accidental Touches & Pocket Dialing',
    category: 'Display',
    diagnosis: 'Proximity detection inactive while phone is in pockets, purses, or dark compartments.',
    likelyCauses: [
      'Accidental touch protection toggle turned off',
      'Touch sensitivity feature overly boosted for thick screen protectors',
      'Double tap to wake triggering inside fabric pocket',
    ],
    keywords: ['accidental touch', 'pocket dial', 'pocket dialing', 'types by itself', 'touches in pocket', 'screen touches itself'],
    fixes: [
      {
        id: 'fix-accidental-touch-protection',
        title: 'Turn on Accidental Touch Protection',
        description: 'Uses front light and proximity sensors to prevent screen recognition in dark enclosed spaces.',
        whyItHelps: 'Blocks capacitive input whenever the phone detects it is inside a pocket or bag.',
        expectedImpact: 'Completely eliminates phantom touches and pocket calls',
        samsungPath: ['Settings', 'Display', 'Accidental touch protection'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'accidental_touch',
        action: {
          id: 'fix-accidental-touch-protection',
          title: 'Turn on Accidental Touch Protection',
          type: 'TOGGLE_ON',
          settingKey: 'accidentalTouchProtection',
          targetValue: true,
          destination: 'settings/display',
          destinationPath: ['Settings', 'Display', 'Accidental touch protection'],
          highlightNode: 'Accidental touch protection',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Zero pocket dialing',
          reason: 'Blocks phantom screen touches when proximity sensor is obscured.',
          steps: ['Open Settings', 'Tap Display', 'Toggle Accidental touch protection to ON'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/display', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Accidental touch protection', durationMs: 700 },
            { type: 'TOGGLE', target: 'accidentalTouchProtection', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Accidental touch protection enabled' },
          ],
        },
      },
      {
        id: 'fix-screen-timeout',
        title: 'Shorten Screen Timeout to 30 Seconds',
        description: 'Automatically turns off display after 30 seconds of inactivity.',
        whyItHelps: 'Ensures the screen doesn\'t stay awake and register touches when slipping the phone into a pocket.',
        expectedImpact: 'Saves battery and locks screen faster',
        samsungPath: ['Settings', 'Display', 'Screen timeout'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'screen_timeout',
      },
    ],
  },

  // =========================================================================
  // 4. STORAGE / PERFORMANCE CATEGORY
  // =========================================================================
  {
    problemId: 'storage-full',
    title: 'Internal Storage Full',
    category: 'Storage / Performance',
    diagnosis: 'Accumulated app cache, redundant media files, and unemptied recycle bins filling internal storage.',
    likelyCauses: [
      'Application cache buildup (messaging apps, social media, video streaming)',
      'Unemptied Samsung Gallery and My Files trash bins',
      'Large downloaded system update packages or uncompressed files',
    ],
    keywords: ['storage full', 'storage', 'low storage', 'out of storage', 'clean storage', 'storage space', 'memory full', 'no space left'],
    fixes: [
      {
        id: 'fix-storage-cleaner',
        title: 'Clean Storage Junk & Cache Files',
        description: 'Purges orphaned temporary application cache and system logs without deleting personal data.',
        whyItHelps: 'Safely recovers gigabytes of flash storage space without risking user photos, videos, or documents.',
        expectedImpact: 'Frees up ~4.8 GB of cached temporary storage',
        samsungPath: ['Settings', 'Device care', 'Storage'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'storage_cleaner',
        action: {
          id: 'fix-storage-cleaner',
          title: 'Clean Storage Junk & Cache Files',
          type: 'TOGGLE_ON',
          settingKey: 'storageCleaned',
          targetValue: true,
          destination: 'settings/storage',
          destinationPath: ['Settings', 'Device care', 'Storage'],
          highlightNode: 'Clean now',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Frees up ~4.8 GB of cached temp files',
          reason: 'Removes orphaned application cache files and duplicate trash bins without deleting user photos.',
          steps: ['Open Settings', 'Tap Device care', 'Tap Storage', 'Tap Clean now'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/storage', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Clean now', durationMs: 700 },
            { type: 'TOGGLE', target: 'storageCleaned', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Storage cleaned: 4.8 GB freed' },
          ],
        },
      },
      {
        id: 'fix-auto-optimization-storage',
        title: 'Enable Device Care Auto Optimization',
        description: 'Automatically cleans working RAM and restarts phone during idle hours to clear memory leaks.',
        whyItHelps: 'Ensures the operating system periodically clears swap files and resets system daemons.',
        expectedImpact: 'Maintains consistent read/write storage speed',
        samsungPath: ['Settings', 'Device care', 'Auto optimization'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'auto_optimization',
      },
    ],
  },
  {
    problemId: 'phone-sluggish',
    title: 'Phone Sluggish & Apps Freezing',
    category: 'Storage / Performance',
    diagnosis: 'Excessive background applications consuming working RAM, memory fragmentation, or storage read-write bottlenecks.',
    likelyCauses: [
      'Too many background apps running concurrently in RAM',
      'Accumulated memory leaks from unoptimized apps',
      'Virtual RAM Plus paging overhead causing micro-stutter',
    ],
    keywords: ['slow', 'phone slow', 'lagging', 'phone lagging', 'apps freezing', 'app freeze', 'device slow', 'sluggish', 'phone is slow'],
    fixes: [
      {
        id: 'fix-device-care-optimize',
        title: 'Run Device Care Auto Optimization',
        description: 'Cleans rogue background apps, flushes idle memory buffers, and checks for battery drain.',
        whyItHelps: 'Reclaims up to 2.5 GB of active RAM and terminates frozen background execution threads.',
        expectedImpact: 'Restores instant app opening responsiveness',
        samsungPath: ['Settings', 'Device care', 'Auto optimization'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'auto_optimization',
        action: {
          id: 'fix-device-care-optimize',
          title: 'Enable Auto Optimization',
          type: 'TOGGLE_ON',
          settingKey: 'autoOptimization',
          targetValue: true,
          destination: 'settings/device-care',
          destinationPath: ['Settings', 'Device care', 'Auto optimization'],
          highlightNode: 'Auto optimization',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Reclaims up to 2.5 GB of active RAM',
          reason: 'Automatically closes background tasks and optimizes memory when phone is idle.',
          steps: ['Open Settings', 'Tap Device care', 'Turn on Auto optimization'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/device-care', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Auto optimization', durationMs: 700 },
            { type: 'TOGGLE', target: 'autoOptimization', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'Auto optimization enabled' },
          ],
        },
      },
      {
        id: 'fix-clean-cache-performance',
        title: 'Purge Cached Junk Files',
        description: 'Frees flash storage blocks so system paging operates at peak SSD read/write speeds.',
        whyItHelps: 'Flash storage suffers high I/O latency when nearly full; clearing cache restores IOPS performance.',
        expectedImpact: 'Faster file read speeds and zero app launch lag',
        samsungPath: ['Settings', 'Device care', 'Storage'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'storage_cleaner',
      },
      {
        id: 'fix-motion-smoothness-performance',
        title: 'Verify Adaptive 120Hz Refresh Rate',
        description: 'Ensures UI animations render at a full 120 FPS without framerate drops.',
        whyItHelps: 'Eliminates stutter during multitasking gestures and app switching.',
        expectedImpact: 'Fluid 120Hz visual navigation',
        samsungPath: ['Settings', 'Display', 'Motion smoothness'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'motion_smoothness',
      },
    ],
  },

  // =========================================================================
  // 5. NOTIFICATIONS CATEGORY
  // =========================================================================
  {
    problemId: 'whatsapp-notifications',
    title: 'WhatsApp Notifications Not Arriving or Delayed',
    category: 'Notifications',
    diagnosis: 'One UI battery optimization putting WhatsApp into sleep, background data restriction, or Do Not Disturb silencing alerts.',
    likelyCauses: [
      'WhatsApp added to Sleeping or Deep Sleeping apps in Battery settings',
      'Per-app notification channel permissions disabled in One UI Apps menu',
      'Do Not Disturb mode currently active with no WhatsApp bypass rule',
      'Background data restriction active when Mobile Data is on',
    ],
    keywords: ['whatsapp notification', 'whatsapp notifications', 'whatsapp not showing', 'whatsapp message delayed', 'whatsapp alert', 'messages not coming'],
    fixes: [
      {
        id: 'fix-whatsapp-notification-permission',
        title: 'Enable WhatsApp App Notifications',
        description: 'Grants master notification permissions and unlocks banner pop-ups for WhatsApp.',
        whyItHelps: 'Restores instant lock screen banners, vibration alerts, and app icon badges for new messages.',
        expectedImpact: 'Immediate delivery of all incoming message alerts',
        samsungPath: ['Settings', 'Apps', 'WhatsApp', 'Notifications'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'app_notifications',
        action: {
          id: 'fix-whatsapp-notification-permission',
          title: 'Enable WhatsApp Notifications',
          type: 'TOGGLE_ON',
          settingKey: 'appNotifications',
          targetValue: true,
          destination: 'settings/apps',
          destinationPath: ['Settings', 'Apps', 'WhatsApp', 'Notifications'],
          highlightNode: 'Allow notifications',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Immediate delivery of WhatsApp messages',
          reason: 'Restores push notification permissions for the WhatsApp messaging service.',
          steps: ['Open Settings', 'Tap Apps', 'Select WhatsApp', 'Tap Notifications', 'Turn on Allow notifications'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/apps', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'WhatsApp', durationMs: 700 },
            { type: 'TOGGLE', target: 'appNotifications', value: true, durationMs: 500 },
            { type: 'COMPLETE', message: 'WhatsApp notifications enabled' },
          ],
        },
      },
      {
        id: 'fix-whatsapp-background-whitelist',
        title: 'Exclude WhatsApp from Sleeping Apps',
        description: 'Adds WhatsApp to Never Sleeping Apps so One UI does not kill its background push service.',
        whyItHelps: 'Ensures the Google FCM background push listener remains active even with phone screen off.',
        expectedImpact: 'Zero message delay when phone is locked',
        samsungPath: ['Settings', 'Battery', 'Background usage limits', 'Never sleeping apps'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'deep_sleeping_apps',
        action: {
          id: 'fix-whatsapp-background-whitelist',
          title: 'Whitelist WhatsApp from Deep Sleep',
          type: 'CONFIG_CHANGE',
          destination: 'settings/battery-usage',
          destinationPath: ['Settings', 'Battery', 'Background usage limits', 'Never sleeping apps'],
          highlightNode: 'Never sleeping apps',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Instant background notification alerts',
          reason: 'Prevents One UI from suspending WhatsApp in the background.',
          steps: ['Open Settings', 'Tap Battery', 'Tap Background usage limits', 'Add WhatsApp to Never sleeping apps'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/battery-usage', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Never sleeping apps', durationMs: 700 },
            { type: 'COMPLETE', message: 'WhatsApp whitelisted from battery restrictions' },
          ],
        },
      },
      {
        id: 'fix-disable-dnd',
        title: 'Turn off Do Not Disturb',
        description: 'Disables system-wide Do Not Disturb mode so notification sounds and banners appear normally.',
        whyItHelps: 'Do Not Disturb suppresses all heads-up banners, sound alerts, and lock screen pop-ups.',
        expectedImpact: 'Restores all audible alerts and pop-up banners',
        samsungPath: ['Settings', 'Notifications', 'Do not disturb'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'do_not_disturb',
        action: {
          id: 'fix-disable-dnd',
          title: 'Turn off Do Not Disturb',
          type: 'TOGGLE_OFF',
          settingKey: 'doNotDisturb',
          targetValue: false,
          destination: 'settings/generic/Notifications',
          destinationPath: ['Settings', 'Notifications', 'Do not disturb'],
          highlightNode: 'Do not disturb',
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Unmutes all notification pop-ups',
          reason: 'Turns off Do Not Disturb to let alerts through.',
          steps: ['Open Settings', 'Tap Notifications', 'Toggle Do not disturb to OFF'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'settings', durationMs: 400 },
            { type: 'NAVIGATE', screen: 'settings/generic/Notifications', durationMs: 600 },
            { type: 'HIGHLIGHT', target: 'Do not disturb', durationMs: 700 },
            { type: 'TOGGLE', target: 'doNotDisturb', value: false, durationMs: 500 },
            { type: 'COMPLETE', message: 'Do Not Disturb turned off' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'instagram-notifications',
    title: 'Instagram Notifications Missing or Delayed',
    category: 'Notifications',
    diagnosis: 'App notifications disabled in system settings, or background activity killed by Samsung battery saver.',
    likelyCauses: [
      'Notification permission revoked for Instagram',
      'Instagram put into Sleeping apps list by Device Care',
      'Background data usage toggled off under Mobile Data settings',
    ],
    keywords: ['instagram notification', 'instagram notifications', 'instagram alerts', 'instagram dm notification'],
    fixes: [
      {
        id: 'fix-instagram-notification-permission',
        title: 'Enable Instagram Notifications in Apps',
        description: 'Restores master notification permissions and unlocks direct message alerts.',
        whyItHelps: 'Ensures Instagram has authorization to send lock screen and pop-up notifications.',
        expectedImpact: 'Immediate delivery of direct messages and activity alerts',
        samsungPath: ['Settings', 'Apps', 'Instagram', 'Notifications'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'app_notifications',
      },
      {
        id: 'fix-instagram-never-sleep',
        title: 'Remove Instagram from Sleeping Apps',
        description: 'Exempts Instagram from aggressive One UI background termination.',
        whyItHelps: 'Keeps Instagram\'s push sync worker alive in the background.',
        expectedImpact: 'Real-time DM notifications',
        samsungPath: ['Settings', 'Battery', 'Background usage limits'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'deep_sleeping_apps',
      },
    ],
  },
  {
    problemId: 'gmail-notifications',
    title: 'Gmail Notifications Not Arriving or Delayed',
    category: 'Notifications',
    diagnosis: 'Google account sync disabled, battery optimization throttling sync, or background data restricted.',
    likelyCauses: [
      'Auto-sync data turned off in Samsung Accounts & Backup settings',
      'Gmail app placed in Deep Sleep list by adaptive battery routines',
      'Gmail notification priority set to High priority only',
    ],
    keywords: ['gmail', 'gmail notification', 'email notification', 'gmail not syncing', 'gmail delayed', 'email not arriving'],
    fixes: [
      {
        id: 'fix-gmail-notifications-permission',
        title: 'Enable Gmail App Notifications',
        description: 'Turns on push alert notifications for all incoming emails.',
        whyItHelps: 'Allows Gmail to wake the lock screen and play sound alerts upon receiving new emails.',
        expectedImpact: 'Instant notification on new email arrival',
        samsungPath: ['Settings', 'Apps', 'Gmail', 'Notifications'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'app_notifications',
      },
      {
        id: 'fix-gmail-remove-sleep',
        title: 'Exclude Gmail from Background Battery Limits',
        description: 'Guarantees Google Sync services remain active 24/7.',
        whyItHelps: 'Prevents Android OS from pausing email IMAP/Exchange synchronization.',
        expectedImpact: 'Zero delay on important work and personal emails',
        samsungPath: ['Settings', 'Battery', 'Background usage limits', 'Never sleeping apps'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'deep_sleeping_apps',
      },
    ],
  },

  // =========================================================================
  // 6. APPS CATEGORY
  // =========================================================================
  {
    problemId: 'youtube-troubleshooting',
    title: 'YouTube App Buffering or Crashing',
    category: 'Apps',
    diagnosis: 'Corrupted playback cache, outdated app binaries, or hardware video decoding frame buffer stall.',
    likelyCauses: [
      'Accumulated corrupted video cache in YouTube storage',
      'Unstable network connection or low Wi-Fi bandwidth',
      'Background app memory starvation',
    ],
    keywords: ['youtube', 'youtube crashing', 'youtube buffering', 'youtube lag', 'video buffering'],
    fixes: [
      {
        id: 'fix-youtube-clear-cache',
        title: 'Clear YouTube App Cache',
        description: 'Flushes corrupt thumbnail caches and cached video segments.',
        whyItHelps: 'Forces YouTube to rebuild its media buffer cleanly from Google servers.',
        expectedImpact: 'Resolves playback stutter and app crash on launch',
        samsungPath: ['Settings', 'Apps', 'YouTube', 'Storage', 'Clear cache'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'app_notifications',
      },
      {
        id: 'fix-launch-youtube',
        title: 'Launch YouTube (Web Fallback)',
        description: 'Opens YouTube service in web browser if native app is stalled.',
        whyItHelps: 'Provides immediate streaming access without waiting for app reinstall.',
        expectedImpact: 'Instant video streaming access',
        samsungPath: ['Home', 'YouTube'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'app_launch_youtube',
        action: {
          id: 'fix-launch-youtube',
          title: 'Launch YouTube',
          type: 'OPEN_APP',
          appPackage: 'com.google.android.youtube',
          appName: 'YouTube',
          destination: 'home',
          destinationPath: ['Home', 'YouTube'],
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Direct app or web fallback launch',
          reason: 'Opens YouTube to resume video streaming.',
          steps: ['Open YouTube'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'home', durationMs: 500 },
            { type: 'COMPLETE', message: 'YouTube launched via web fallback' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'google-maps-troubleshooting',
    title: 'Google Maps GPS Inaccuracy or Lag',
    category: 'Apps',
    diagnosis: 'High accuracy location disabled, compass calibration drift, or location permission restricted to while using app only.',
    likelyCauses: [
      'Precise location permission disabled in Samsung Security & privacy',
      'Power saving mode limiting GNSS / GPS satellite polling frequency',
      'Heavy offline cache slowing route calculations',
    ],
    keywords: ['maps', 'google maps', 'gps', 'gps not working', 'location inaccurate', 'maps lagging'],
    fixes: [
      {
        id: 'fix-maps-location-permission',
        title: 'Enable Precise Location Permission',
        description: 'Grants high-accuracy dual-frequency GNSS satellite access to Google Maps.',
        whyItHelps: 'Enables GPS, GLONASS, and Galileo multi-constellation satellite tracking for sub-meter accuracy.',
        expectedImpact: 'Sub-meter navigation accuracy and instant turn recalculation',
        samsungPath: ['Settings', 'Security and privacy', 'Privacy', 'Location', 'Google Maps'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'app_notifications',
      },
      {
        id: 'fix-launch-google-maps',
        title: 'Open Google Maps',
        description: 'Launches Google Maps interface or opens mobile web counterpart.',
        whyItHelps: 'Provides immediate route navigation and traffic status.',
        expectedImpact: 'Instant map navigation access',
        samsungPath: ['Home', 'Google Maps'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'app_launch_maps',
        action: {
          id: 'fix-launch-google-maps',
          title: 'Launch Google Maps',
          type: 'OPEN_APP',
          appPackage: 'com.google.android.apps.maps',
          appName: 'Google Maps',
          destination: 'home',
          destinationPath: ['Home', 'Google Maps'],
          requiresConfirmation: false,
          canAutoApply: true,
          risk: 'low',
          estimatedImpact: 'Instant GPS map navigation',
          reason: 'Launches Google Maps navigation service.',
          steps: ['Open Google Maps'],
          demoSequence: [
            { type: 'NAVIGATE', screen: 'home', durationMs: 500 },
            { type: 'COMPLETE', message: 'Google Maps launched via web fallback' },
          ],
        },
      },
    ],
  },
  {
    problemId: 'samsung-internet-troubleshooting',
    title: 'Samsung Internet Browser Lag & Page Crashes',
    category: 'Apps',
    diagnosis: 'Accumulated web browsing cache, cookies, or conflicting content blockers causing render memory pressure.',
    likelyCauses: [
      'Excessive browsing history and website cache stored in memory',
      'High tab count exhausting active browser RAM allocation',
      'Aggressive ad blocker blocking legitimate webpage scripts',
    ],
    keywords: ['samsung internet', 'browser crash', 'browser slow', 'internet lag', 'webpage not loading'],
    fixes: [
      {
        id: 'fix-samsung-internet-clear-cache',
        title: 'Clear Samsung Internet Browsing Data',
        description: 'Purges cached web assets, cookies, and temporary script files.',
        whyItHelps: 'Frees web rendering engine memory and resolves website script execution errors.',
        expectedImpact: 'Up to 2x faster page rendering and zero tab crashes',
        samsungPath: ['Settings', 'Apps', 'Samsung Internet', 'Storage', 'Clear cache'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'storage_cleaner',
      },
      {
        id: 'fix-samsung-internet-clean-storage',
        title: 'Clean Storage Junk Files',
        description: 'Flushes general system temp files to improve browser storage I/O speed.',
        whyItHelps: 'Accelerates browser database read/write speeds.',
        expectedImpact: 'Smooth tab switching and scrolling',
        samsungPath: ['Settings', 'Device care', 'Storage'],
        risk: 'low',
        canAutoApply: true,
        canDemo: true,
        capabilityId: 'storage_cleaner',
      },
    ],
  },
];

/**
 * Deterministically finds the best matching TroubleshootingPlan for a user query or goal title
 */
export function findTroubleshootingPlan(query: string, goalTitle?: string): TroubleshootingPlan | null {
  const combined = `${query} ${goalTitle || ''}`.toLowerCase();

  // Priority exact matching based on catalog keywords
  let bestPlan: TroubleshootingPlan | null = null;
  let highestScore = 0;

  for (const plan of TROUBLESHOOTING_CATALOG) {
    let score = 0;

    // Check problemId direct mention
    if (combined.includes(plan.problemId.replace(/-/g, ' '))) {
      score += 10;
    }

    // Check title keywords
    const titleWords = plan.title.toLowerCase().split(/\s+/);
    for (const tw of titleWords) {
      if (tw.length > 3 && combined.includes(tw)) {
        score += 2;
      }
    }

    // Check catalog keywords
    for (const kw of plan.keywords) {
      if (combined.includes(kw.toLowerCase())) {
        score += 5;
      }
    }

    if (score > highestScore && score >= 4) {
      highestScore = score;
      bestPlan = plan;
    }
  }

  return bestPlan;
}
